language: ruby
sudo: false
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.3
- jruby
- head
os:
- linux
- osx
matrix:
  exclude:
  - rvm: 1.8.7
    os: osx
  - rvm: 1.9.2
    os: osx
  - rvm: 2.1.0
    os: osx
  - rvm: jruby
    os: osx
addons:
  code_climate:
    repo_token: dbbc732a1a68e8d47a792955b21b0a0018854a658239511a561dff1e0c7a127f